import { Session, Department, Program, Course, Lecturer, Room, AcademicYear, TimetableEntry, Class, ClassCourseAssignment, BulkCourseAssignment } from '../types';

export const sampleSessions: Session[] = [
  {
    id: 'session_1',
    name: 'Regular',
    numberOfYears: 4,
    workingDays: [
      { id: 'wd_1', day: 'monday', isActive: true, startTime: '08:00', endTime: '18:00' },
      { id: 'wd_2', day: 'tuesday', isActive: true, startTime: '08:00', endTime: '18:00' },
      { id: 'wd_3', day: 'wednesday', isActive: true, startTime: '08:00', endTime: '18:00' },
      { id: 'wd_4', day: 'thursday', isActive: true, startTime: '08:00', endTime: '18:00' },
      { id: 'wd_5', day: 'friday', isActive: true, startTime: '08:00', endTime: '18:00' },
    ],
    timeSlots: [
      { id: 'ts_1', startTime: '08:00', endTime: '09:00', isBreak: false },
      { id: 'ts_2', startTime: '09:00', endTime: '10:00', isBreak: false },
      { id: 'ts_3', startTime: '10:00', endTime: '10:15', isBreak: true, breakType: 'short' },
      { id: 'ts_4', startTime: '10:15', endTime: '11:15', isBreak: false },
      { id: 'ts_5', startTime: '11:15', endTime: '12:15', isBreak: false },
      { id: 'ts_6', startTime: '12:15', endTime: '13:15', isBreak: true, breakType: 'lunch' },
      { id: 'ts_7', startTime: '13:15', endTime: '14:15', isBreak: false },
      { id: 'ts_8', startTime: '14:15', endTime: '15:15', isBreak: false },
      { id: 'ts_9', startTime: '15:15', endTime: '15:30', isBreak: true, breakType: 'short' },
      { id: 'ts_10', startTime: '15:30', endTime: '16:30', isBreak: false },
      { id: 'ts_11', startTime: '16:30', endTime: '17:30', isBreak: false },
    ],
    breakTimes: [
      { id: 'bt_1', startTime: '10:00', endTime: '10:15', breakType: 'short' },
      { id: 'bt_2', startTime: '12:15', endTime: '13:15', breakType: 'lunch' },
      { id: 'bt_3', startTime: '15:15', endTime: '15:30', breakType: 'short' },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'session_2',
    name: 'Weekend',
    numberOfYears: 4,
    workingDays: [
      { id: 'wd_6', day: 'saturday', isActive: true, startTime: '09:00', endTime: '17:00' },
      { id: 'wd_7', day: 'sunday', isActive: true, startTime: '09:00', endTime: '17:00' },
    ],
    timeSlots: [
      { id: 'ts_12', startTime: '09:00', endTime: '10:00', isBreak: false },
      { id: 'ts_13', startTime: '10:00', endTime: '11:00', isBreak: false },
      { id: 'ts_14', startTime: '11:00', endTime: '11:15', isBreak: true, breakType: 'short' },
      { id: 'ts_15', startTime: '11:15', endTime: '12:15', isBreak: false },
      { id: 'ts_16', startTime: '12:15', endTime: '13:15', isBreak: true, breakType: 'lunch' },
      { id: 'ts_17', startTime: '13:15', endTime: '14:15', isBreak: false },
      { id: 'ts_18', startTime: '14:15', endTime: '15:15', isBreak: false },
      { id: 'ts_19', startTime: '15:15', endTime: '15:30', isBreak: true, breakType: 'short' },
      { id: 'ts_20', startTime: '15:30', endTime: '16:30', isBreak: false },
    ],
    breakTimes: [
      { id: 'bt_4', startTime: '11:00', endTime: '11:15', breakType: 'short' },
      { id: 'bt_5', startTime: '12:15', endTime: '13:15', breakType: 'lunch' },
      { id: 'bt_6', startTime: '15:15', endTime: '15:30', breakType: 'short' },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const sampleDepartments: Department[] = [
  {
    id: 'dept_1',
    name: 'Computer Science',
    code: 'CS',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'dept_2',
    name: 'Electrical Engineering',
    code: 'EE',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'dept_3',
    name: 'Business Administration',
    code: 'BA',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const samplePrograms: Program[] = [
  {
    id: 'prog_1',
    name: 'BSc Computer Science',
    code: 'BSCS',
    departmentId: 'dept_1',
    sessionId: 'session_1',
    degreeType: 'BSc',
    duration: 4,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prog_2',
    name: 'BSc Cybersecurity',
    code: 'BSCC',
    departmentId: 'dept_1',
    sessionId: 'session_1',
    degreeType: 'BSc',
    duration: 4,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prog_3',
    name: 'BSc IT Education',
    code: 'BSITE',
    departmentId: 'dept_1',
    sessionId: 'session_1',
    degreeType: 'BSc',
    duration: 4,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prog_4',
    name: 'BSc Electrical Engineering',
    code: 'BSEE',
    departmentId: 'dept_2',
    sessionId: 'session_1',
    degreeType: 'BSc',
    duration: 4,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prog_5',
    name: 'BSc Business Administration',
    code: 'BSBA',
    departmentId: 'dept_3',
    sessionId: 'session_2',
    degreeType: 'BSc',
    duration: 4,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const sampleLecturers: Lecturer[] = [
  {
    id: 'lect_1',
    name: 'Dr. John Smith',
    departmentId: 'dept_1',
    programs: ['prog_1', 'prog_2', 'prog_3'],
    courses: ['course_1', 'course_3'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'lect_2',
    name: 'Prof. Sarah Johnson',
    departmentId: 'dept_1',
    programs: ['prog_1', 'prog_2', 'prog_3'],
    courses: ['course_2', 'course_4'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'lect_3',
    name: 'Dr. Michael Brown',
    departmentId: 'dept_2',
    programs: ['prog_4'],
    courses: ['course_5', 'course_6'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'lect_4',
    name: 'Prof. Emily Davis',
    departmentId: 'dept_3',
    programs: ['prog_5'],
    courses: ['course_7', 'course_8'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const sampleRooms: Room[] = [
  {
    id: 'room_1',
    name: 'Lecture Hall A',
    building: 'Main Building',
    floor: '1',
    capacity: 150,
    roomType: 'lecture_hall',
    facilities: ['Projector', 'Whiteboard', 'Sound System'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'room_2',
    name: 'Computer Lab 1',
    building: 'Technology Building',
    floor: '2',
    capacity: 30,
    roomType: 'computer_lab',
    facilities: ['Computers', 'Projector', 'Whiteboard'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'room_3',
    name: 'Seminar Room B',
    building: 'Main Building',
    floor: '3',
    capacity: 25,
    roomType: 'seminar_room',
    facilities: ['Projector', 'Whiteboard'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'room_4',
    name: 'Laboratory 2',
    building: 'Engineering Building',
    floor: '1',
    capacity: 20,
    roomType: 'laboratory',
    facilities: ['Lab Equipment', 'Safety Equipment', 'Whiteboard'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const sampleCourses: Course[] = [
  {
    id: 'course_1',
    name: 'Introduction to Programming',
    code: 'ITC121',
    creditHours: 3,
    departmentId: 'dept_1',
    programId: 'prog_1',
    sessionId: 'session_1',
    yearLevel: 1,
    semester: 1,
    isCore: true,
    lecturerId: 'lect_1',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'course_2',
    name: 'Data Structures and Algorithms',
    code: 'ITC231',
    creditHours: 4,
    departmentId: 'dept_1',
    programId: 'prog_1',
    sessionId: 'session_1',
    yearLevel: 2,
    semester: 1,
    isCore: true,
    lecturerId: 'lect_2',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'course_3',
    name: 'Advanced Programming',
    code: 'ITC351',
    creditHours: 3,
    departmentId: 'dept_1',
    programId: 'prog_1',
    sessionId: 'session_1',
    yearLevel: 3,
    semester: 1,
    isCore: true,
    lecturerId: 'lect_1',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'course_4',
    name: 'Software Engineering',
    code: 'ITC472',
    creditHours: 4,
    departmentId: 'dept_1',
    programId: 'prog_1',
    sessionId: 'session_1',
    yearLevel: 4,
    semester: 2,
    isCore: true,
    lecturerId: 'lect_2',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'course_5',
    name: 'Circuit Theory',
    code: 'ELE121',
    creditHours: 3,
    departmentId: 'dept_2',
    programId: 'prog_4',
    sessionId: 'session_1',
    yearLevel: 1,
    semester: 1,
    isCore: true,
    lecturerId: 'lect_3',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'course_6',
    name: 'Power Systems',
    code: 'ELE351',
    creditHours: 3,
    departmentId: 'dept_2',
    programId: 'prog_4',
    sessionId: 'session_1',
    yearLevel: 3,
    semester: 1,
    isCore: true,
    lecturerId: 'lect_3',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'course_7',
    name: 'Business Management',
    code: 'BUS121',
    creditHours: 3,
    departmentId: 'dept_3',
    programId: 'prog_5',
    sessionId: 'session_2',
    yearLevel: 1,
    semester: 1,
    isCore: true,
    lecturerId: 'lect_4',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'course_8',
    name: 'Marketing Strategy',
    code: 'BUS252',
    creditHours: 3,
    departmentId: 'dept_3',
    programId: 'prog_5',
    sessionId: 'session_2',
    yearLevel: 2,
    semester: 2,
    isCore: true,
    lecturerId: 'lect_4',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const sampleAcademicYears: AcademicYear[] = [
  {
    id: 'ay_1',
    name: '2023-2024',
    startDate: new Date('2023-09-01'),
    endDate: new Date('2024-06-30'),
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'ay_2',
    name: '2024-2025',
    startDate: new Date('2024-09-01'),
    endDate: new Date('2025-06-30'),
    isActive: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const sampleTimetableEntries: TimetableEntry[] = [
  {
    id: 'entry_1',
    sessionId: 'session_1',
    departmentId: 'dept_1',
    programId: 'prog_1',
    courseId: 'course_1',
    lecturerId: 'lect_1',
    roomId: 'room_1',
    dayOfWeek: 1, // Monday
    startTime: '08:00',
    endTime: '09:00',
    academicYearId: 'ay_1',
    semester: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'entry_2',
    sessionId: 'session_1',
    departmentId: 'dept_1',
    programId: 'prog_1',
    courseId: 'course_2',
    lecturerId: 'lect_2',
    roomId: 'room_2',
    dayOfWeek: 1, // Monday
    startTime: '09:00',
    endTime: '10:00',
    academicYearId: 'ay_1',
    semester: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'entry_3',
    sessionId: 'session_1',
    departmentId: 'dept_2',
    programId: 'prog_4',
    courseId: 'course_5',
    lecturerId: 'lect_3',
    roomId: 'room_4',
    dayOfWeek: 2, // Tuesday
    startTime: '08:00',
    endTime: '09:00',
    academicYearId: 'ay_1',
    semester: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'entry_4',
    sessionId: 'session_2',
    departmentId: 'dept_3',
    programId: 'prog_5',
    courseId: 'course_7',
    lecturerId: 'lect_4',
    roomId: 'room_3',
    dayOfWeek: 6, // Saturday
    startTime: '09:00',
    endTime: '10:00',
    academicYearId: 'ay_1',
    semester: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const sampleClasses: Class[] = [
  {
    id: 'class_1',
    name: 'A',
    sessionId: 'session_1',
    departmentId: 'dept_1',
    programId: 'prog_1',
    yearLevel: 1,
    semester: 1,
    studentCount: 100,
    maxCapacity: 100,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'class_2',
    name: 'B',
    sessionId: 'session_1',
    departmentId: 'dept_1',
    programId: 'prog_1',
    yearLevel: 1,
    semester: 1,
    studentCount: 100,
    maxCapacity: 100,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'class_3',
    name: 'C',
    sessionId: 'session_1',
    departmentId: 'dept_1',
    programId: 'prog_1',
    yearLevel: 1,
    semester: 1,
    studentCount: 100,
    maxCapacity: 100,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'class_4',
    name: 'D',
    sessionId: 'session_1',
    departmentId: 'dept_1',
    programId: 'prog_1',
    yearLevel: 1,
    semester: 1,
    studentCount: 100,
    maxCapacity: 100,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'class_5',
    name: 'E',
    sessionId: 'session_1',
    departmentId: 'dept_1',
    programId: 'prog_1',
    yearLevel: 1,
    semester: 1,
    studentCount: 100,
    maxCapacity: 100,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'class_6',
    name: 'A',
    sessionId: 'session_1',
    departmentId: 'dept_1',
    programId: 'prog_1',
    yearLevel: 2,
    semester: 1,
    studentCount: 80,
    maxCapacity: 100,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'class_7',
    name: 'A',
    sessionId: 'session_1',
    departmentId: 'dept_2',
    programId: 'prog_4',
    yearLevel: 1,
    semester: 1,
    studentCount: 60,
    maxCapacity: 80,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'class_8',
    name: 'A',
    sessionId: 'session_2',
    departmentId: 'dept_3',
    programId: 'prog_5',
    yearLevel: 1,
    semester: 1,
    studentCount: 45,
    maxCapacity: 50,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Add classes for Cybersecurity and IT Education programs
  {
    id: 'class_9',
    name: 'A',
    sessionId: 'session_1',
    departmentId: 'dept_1',
    programId: 'prog_2', // Cybersecurity
    yearLevel: 1,
    semester: 1,
    studentCount: 75,
    maxCapacity: 80,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'class_10',
    name: 'A',
    sessionId: 'session_1',
    departmentId: 'dept_1',
    programId: 'prog_3', // IT Education
    yearLevel: 1,
    semester: 1,
    studentCount: 60,
    maxCapacity: 70,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const sampleClassCourseAssignments: ClassCourseAssignment[] = [
  // IT Department Level 100 - All classes take the same courses
  {
    id: 'cca_1',
    classId: 'class_1',
    courseId: 'course_1',
    sessionId: 'session_1',
    departmentId: 'dept_1',
    programId: 'prog_1',
    yearLevel: 1,
    semester: 1,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'cca_2',
    classId: 'class_2',
    courseId: 'course_1',
    sessionId: 'session_1',
    departmentId: 'dept_1',
    programId: 'prog_1',
    yearLevel: 1,
    semester: 1,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'cca_3',
    classId: 'class_3',
    courseId: 'course_1',
    sessionId: 'session_1',
    departmentId: 'dept_1',
    programId: 'prog_1',
    yearLevel: 1,
    semester: 1,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'cca_4',
    classId: 'class_4',
    courseId: 'course_1',
    sessionId: 'session_1',
    departmentId: 'dept_1',
    programId: 'prog_1',
    yearLevel: 1,
    semester: 1,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'cca_5',
    classId: 'class_5',
    courseId: 'course_1',
    sessionId: 'session_1',
    departmentId: 'dept_1',
    programId: 'prog_1',
    yearLevel: 1,
    semester: 1,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Add more course assignments for other courses and levels
  {
    id: 'cca_6',
    classId: 'class_6',
    courseId: 'course_2',
    sessionId: 'session_1',
    departmentId: 'dept_1',
    programId: 'prog_1',
    yearLevel: 2,
    semester: 1,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'cca_7',
    classId: 'class_7',
    courseId: 'course_5',
    sessionId: 'session_1',
    departmentId: 'dept_2',
    programId: 'prog_4',
    yearLevel: 1,
    semester: 1,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'cca_8',
    classId: 'class_8',
    courseId: 'course_7',
    sessionId: 'session_2',
    departmentId: 'dept_3',
    programId: 'prog_5',
    yearLevel: 1,
    semester: 1,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const sampleBulkCourseAssignments: BulkCourseAssignment[] = [
  {
    id: 'bca_1',
    sessionId: 'session_1',
    departmentId: 'dept_1',
    programId: 'prog_1',
    yearLevel: 1,
    semester: 1,
    courseIds: ['course_1'],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'bca_2',
    sessionId: 'session_1',
    departmentId: 'dept_1',
    programId: 'prog_1',
    yearLevel: 2,
    semester: 1,
    courseIds: ['course_2'],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'bca_3',
    sessionId: 'session_1',
    departmentId: 'dept_2',
    programId: 'prog_4',
    yearLevel: 1,
    semester: 1,
    courseIds: ['course_5'],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'bca_4',
    sessionId: 'session_2',
    departmentId: 'dept_3',
    programId: 'prog_5',
    yearLevel: 1,
    semester: 1,
    courseIds: ['course_7'],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Add more assignments to show different scenarios
  {
    id: 'bca_5',
    sessionId: 'session_1',
    departmentId: 'dept_1',
    programId: 'prog_1',
    yearLevel: 3,
    semester: 1,
    courseIds: ['course_3'],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'bca_6',
    sessionId: 'session_1',
    departmentId: 'dept_1',
    programId: 'prog_1',
    yearLevel: 4,
    semester: 2,
    courseIds: ['course_4'],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'bca_7',
    sessionId: 'session_1',
    departmentId: 'dept_2',
    programId: 'prog_4',
    yearLevel: 3,
    semester: 1,
    courseIds: ['course_6'],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'bca_8',
    sessionId: 'session_2',
    departmentId: 'dept_3',
    programId: 'prog_5',
    yearLevel: 2,
    semester: 2,
    courseIds: ['course_8'],
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
